const gameCards = {
  sipIf: {
    classic: [
      "Drink if you've ever pretended to be sober.",
      "Drink if you've texted your ex.",
      "Drink if you've ever lost something on a night out.",
      "Drink if you're wearing black.",
      "Drink if you've ever lied about being on your way.",
      "Drink if you've ever fallen asleep at a party.",
      "Drink if you've ever deleted messages to hide something.",
      "Drink if you have an iPhone.",
      "Drink if you've ever flirted for free drinks.",
      "Drink if you've ever ghosted someone.",
      "Last person to stand up drinks.",
      "Drink if you've ever fake-laughed at a joke.",
      "Drink if you're single.",
      "The loudest player drinks.",
      "Drink if you've ever sent an embarrassing drunk message.",
      "Drink if you've ever blamed your friend for something you did.",
      "Drink if you're wearing white.",
      "Drink if you've ever missed a class because of a hangover.",
      "Drink if you've ever pretended to know the lyrics to a song.",
      "Drink if you've ordered food after midnight.",
      "Drink if you've ever lost your keys on a night out.",
      "Drink if you've ever blamed autocorrect for a message.",
      "Drink if you've ever been caught lying.",
      "Drink if you're wearing trainers.",
      "Drink if you've ever rewatched the same show more than twice.",
      "Drink if you've ever forgotten someone's name immediately after meeting them.",
      "Drink if you've ever fallen asleep during a movie.",
      "Drink if you have brown eyes.",
      "Drink if you've ever screenshotted a conversation.",
      "Drink if you've ever cancelled plans last minute.",
      "Drink if you've ever tripped over in public.",
      "Drink if you're tired right now.",
      "Drink if you've ever laughed at the wrong moment.",
      "Drink if you've ever snoozed your alarm more than three times.",
      "Drink if you've ever forgotten why you walked into a room.",
      "Drink if you've ever waved back at someone who wasn't waving at you.",
      "Drink if you have a pet.",
      "Drink if you've ever eaten food off the floor.",
      "Drink if you've ever cried laughing.",
      "Drink if you've ever stayed up all night accidentally.",
      "Drink if your battery is below 20%.",
      "Drink if you've ever dropped your phone on your face.",
  
      "Drink if you think {player} would survive longest in a horror movie.",
      "{player} drinks if they have made you laugh tonight.",
      "Drink if you would trust {player} with your phone.",
      "{player} drinks if they are most likely to make the group laugh.",
      "Drink if {player} has ever convinced you to do something chaotic.",
      "Drink if you think {player} would get lost on a night out.",
      "{player} drinks if they have the best music taste.",
      "Drink if you think {player} would survive a zombie apocalypse.",
      "{player} drinks if they look like they need one.",
      "{player} drinks if they are most likely to order food later.",
      "Drink if you would let {player} choose the playlist.",
      "{player} drinks if they are the group comedian.",
      "Drink if you think {player} would accidentally expose a secret.",
      "Drink if you think {player} would be the first to fall asleep.",
      "{player} drinks if they are the main character tonight.",
      "Drink if you think {player} would be terrible at keeping a straight face.",
      "{player} drinks if they have made you laugh today.",
      "Drink if you think {player} would make the worst getaway driver."
    ],
  
    spicy: [
      "Drink if you've ever kissed someone in this room.",
      "Drink if you've ever had a crush on a friend.",
      "Drink if you've ever sent a risky text.",
      "Drink if you've ever regretted a message the next morning.",
      "Drink if you've ever flirted with someone just for attention.",
      "Drink if you've ever kissed someone and kept it secret.",
      "Drink if you've ever checked someone's socials more than once in a day.",
      "Drink if you've ever had a situationship.",
      "Drink if you've ever lied about who you were texting.",
      "The biggest heartbreaker drinks.",
      "Drink if you've ever had a sneaky link.",
      "Drink if you've ever gone back to someone you said you were done with.",
      "Drink if you've ever deleted a message before someone could read it.",
      "The biggest flirt drinks.",
      "Drink if you've ever fancied someone you definitely shouldn't.",
      "Drink if you've ever kissed someone and regretted it.",
      "Drink if you've ever flirted with two people on the same night.",
      "Drink if you've ever saved someone's photo.",
      "Drink if you've ever had a crush on someone already taken.",
      "The person with the best game drinks.",
      "Drink if you've ever sent a message and instantly panicked.",
      "Drink if you've ever lied about being single.",
      "Drink if you've ever had a secret crush in the group.",
      "Drink if you've ever gone through someone's tagged photos.",
      "The person most likely to have a secret admirer drinks.",
      "Drink if you've ever pretended not to care when you definitely did.",
      "Drink if you've ever kissed someone whose name you forgot.",
      "Drink if you've ever had a flirty friendship.",
      "The most mysterious player drinks.",
      "Drink if you've ever hidden a chat.",
      "Drink if you've ever made the first move.",
      "Drink if you've ever been someone's red flag.",
      "The person most likely to have a roster drinks.",
  
      "{player} drinks if you think they are the biggest flirt.",
      "Drink if you think {player} has a secret admirer.",
      "Drink if you'd trust {player} to write a flirty text for you.",
      "{player} drinks if they give main character energy tonight.",
      "Drink if you think {player} would accidentally catch feelings first.",
      "Drink if you think {player} has the best rizz.",
      "{player} drinks if you think they would survive a messy situationship.",
      "Drink if you think {player} is secretly romantic.",
      "{player} drinks if they are most likely to cause harmless drama.",
      "Drink if you think {player} would flirt their way out of trouble.",
      "Drink if you think {player} has unread messages they are avoiding.",
      "{player} drinks if they look like trouble tonight.",
      "Drink if you think {player} has a secret type.",
      "{player} drinks if they would be dangerous on a dating app."
    ],

    girlsNight: [
      "Drink if you've ever hyped your friend up then immediately judged their choice.",
      "Drink if you've ever said 'I'm not going out' and ended up out anyway.",
      "Drink if you've ever helped a friend stalk someone online.",
      "Drink if you've ever taken over a friend's text conversation.",
      "Drink if you've ever said 'he's not worth it' more than once.",
      "Drink if you've ever gone to the toilet as a group.",
      "Drink if you've ever taken 50 photos and only liked one.",
      "Drink if you've ever borrowed something and forgot to give it back.",
      "Drink if you've ever told your friend to block someone.",
      "Drink if you've ever sent screenshots to the group chat.",
      "Drink if you've ever pretended to be calm when you were absolutely not.",
      "Drink if you've ever planned an outfit around one photo.",
      "Drink if you've ever said 'I have nothing to wear' while owning too many clothes.",
      "Drink if you've ever given relationship advice you wouldn't follow yourself.",
      "Drink if you've ever defended your friend even when they were wrong.",
      "Drink if you've ever had a full debrief after a night out.",
      "Drink if you've ever gone out for one drink and came home at a ridiculous time.",
      "Drink if you've ever had a secret code word with your friends.",
      "Drink if you've ever helped a friend escape a conversation.",
      "Drink if you've ever said 'we're leaving' and then stayed another hour.",

      "{player} drinks if they are the group hype person.",
      "{player} drinks if they are most likely to start the group chat drama.",
      "Drink if you would trust {player} to pick your outfit.",
      "{player} drinks if they give the best advice.",
      "Drink if you think {player} would expose someone with receipts.",
      "{player} drinks if they are most likely to say 'I told you so'.",
      "Drink if you think {player} would make the best bridesmaid.",
      "{player} drinks if they are the friend everyone runs to.",
      "Drink if you think {player} would be dangerous with a private story.",
      "{player} drinks if they have main character energy tonight."
    ],

    couples: [
      "Drink if you've ever stolen your partner's food.",
      "Drink if you've ever said 'I'm fine' when you were absolutely not fine.",
      "Drink if you've ever fallen asleep during a film together.",
      "Drink if you've ever argued over where to eat.",
      "Drink if you've ever used your partner as a human radiator.",
      "Drink if you've ever sent a cute message then pretended it wasn't that deep.",
      "Drink if you've ever remembered a tiny detail your partner forgot.",
      "Drink if you've ever taken forever to choose what to watch.",
      "Drink if you've ever been annoyed because they breathed too loudly.",
      "Drink if you've ever stolen a hoodie.",
      "Drink if you've ever said 'you choose' and hated their choice.",
      "Drink if you've ever sent a good morning or goodnight text.",
      "Drink if you've ever had a silly inside joke nobody else understands.",
      "Drink if you've ever been dramatic over a tiny thing.",
      "Drink if you've ever planned a fake future together.",
      "Drink if you've ever got jealous but tried to act normal.",
      "Drink if you've ever kept a cute screenshot.",
      "Drink if you've ever missed someone but refused to say it first.",
      "Drink if you've ever won an argument only because you were louder.",
      "Drink if you've ever said 'I don't mind' and definitely minded.",

      "{player} drinks if they would be the clingier one in a relationship.",
      "Drink if you think {player} would plan the better date.",
      "{player} drinks if they seem like they would steal the blanket.",
      "Drink if you think {player} would be the first to apologise.",
      "{player} drinks if they would remember every anniversary.",
      "Drink if you think {player} gives cute relationship energy.",
      "{player} drinks if they would get jealous but deny it.",
      "Drink if you think {player} would be the better cook in a couple.",
      "{player} drinks if they would send paragraphs after an argument.",
      "Drink if you think {player} would be secretly romantic."
    ],

    chaos: [
      "Drink if you've ever started a night with no plan and ended up somewhere random.",
      "Drink if you've ever made a decision everyone regretted later.",
      "Drink if you've ever shouted 'shots' and ruined the night.",
      "Drink if you've ever lost the group on a night out.",
      "Drink if you've ever woken up with no idea how you got home.",
      "Drink if you've ever said 'this is a bad idea' and did it anyway.",
      "Drink if you've ever broken something and pretended you didn't.",
      "Drink if you've ever caused drama by accident.",
      "Drink if you've ever been the reason the group was late.",
      "Drink if you've ever sent a message you had to apologise for.",
      "Drink if you've ever made friends with a stranger and never saw them again.",
      "Drink if you've ever turned a quiet night into a full event.",
      "Drink if you've ever had to be escorted home by a friend.",
      "Drink if you've ever bought something ridiculous while drunk.",
      "Drink if you've ever had a mysterious bruise after a night out.",
      "Drink if you've ever said 'one more' and meant five more.",
      "Drink if you've ever been banned from making plans.",
      "Drink if you've ever laughed so hard you couldn't breathe.",
      "Drink if you've ever accidentally exposed yourself in a group chat.",
      "Drink if you've ever made the group leave because of your chaos.",

      "{player} drinks if they are most likely to make tonight messy.",
      "Drink if you think {player} would start a chant in public.",
      "{player} drinks if they are the worst influence here.",
      "Drink if you think {player} would lose their phone first.",
      "{player} drinks if they are most likely to wake up confused tomorrow.",
      "Drink if you think {player} would turn a calm night into chaos.",
      "{player} drinks if they are banned from making sensible decisions.",
      "Drink if you think {player} would be the first to suggest shots.",
      "{player} drinks if they have chaotic main character energy.",
      "Drink if you think {player} would accidentally start drama tonight."
    ],

    bestFriends: [
      "Drink if you've ever known exactly what your friend was thinking from one look.",
      "Drink if you've ever laughed at an inside joke nobody else understood.",
      "Drink if you've ever told your friend something before anyone else.",
      "Drink if you've ever borrowed your friend's clothes.",
      "Drink if you've ever defended your friend without knowing the full story.",
      "Drink if you've ever had a friendship argument over something stupid.",
      "Drink if you've ever sent a screenshot before replying.",
      "Drink if you've ever had a full conversation using only facial expressions.",
      "Drink if you've ever remembered an embarrassing story about your friend.",
      "Drink if you've ever been brutally honest with a friend.",
      "Drink if you've ever made plans with your friend and cancelled together.",
      "Drink if you've ever had a nickname only your friends use.",
      "Drink if you've ever been the designated advice giver.",
      "Drink if you've ever kept your friend's secret.",
      "Drink if you've ever known your friend was lying but let it slide.",
      "Drink if you've ever shared food and regretted it.",
      "Drink if you've ever had a friendship tradition.",
      "Drink if you've ever helped your friend get ready.",
      "Drink if you've ever made your friend laugh at the worst possible time.",
      "Drink if you've ever had to explain your friendship to someone else.",

      "{player} drinks if they know the most secrets in this group.",
      "Drink if you would trust {player} with your phone unlocked.",
      "{player} drinks if they are the best person to gossip with.",
      "Drink if you think {player} gives the best advice.",
      "{player} drinks if they are most likely to remember embarrassing stories.",
      "Drink if you think {player} would defend you in public.",
      "{player} drinks if they are the group therapist.",
      "Drink if you think {player} would be your emergency contact.",
      "{player} drinks if they are most likely to expose an inside joke.",
      "Drink if you think {player} knows too much."
    ],

    houseParty: [
      "Drink if you've ever arrived at a house party with no idea whose house it was.",
      "Drink if you've ever controlled the playlist without permission.",
      "Drink if you've ever spilled a drink at a party.",
      "Drink if you've ever danced in someone's kitchen.",
      "Drink if you've ever sat on the stairs during a party.",
      "Drink if you've ever lost your drink and got another one.",
      "Drink if you've ever made friends with someone in the smoking area.",
      "Drink if you've ever eaten party snacks like it was dinner.",
      "Drink if you've ever gone to a party just because someone cute was going.",
      "Drink if you've ever helped clean up and regretted it.",
      "Drink if you've ever left something at someone's house.",
      "Drink if you've ever been too loud in a residential area.",
      "Drink if you've ever had a deep chat in the bathroom.",
      "Drink if you've ever pretended to know someone at a party.",
      "Drink if you've ever been the last to leave.",
      "Drink if you've ever turned up underdressed or overdressed.",
      "Drink if you've ever taken over the aux.",
      "Drink if you've ever gone missing at a house party.",
      "Drink if you've ever had takeaway delivered to a party.",
      "Drink if you've ever said 'whose drink is this?' and drank it anyway.",

      "{player} drinks if they are most likely to control the music.",
      "Drink if you think {player} would be the best host.",
      "{player} drinks if they are most likely to spill a drink.",
      "Drink if you think {player} would start dancing first.",
      "{player} drinks if they would make friends with everyone here.",
      "Drink if you think {player} would be found in the kitchen.",
      "{player} drinks if they are most likely to suggest party games.",
      "Drink if you think {player} would be the last to leave.",
      "{player} drinks if they would accidentally break a house rule.",
      "Drink if you think {player} would make this party better."
    ]
  },
  mostLikely: {
  },
  mostLikely: {
    classic: [
      "Most likely to drunk text their ex?",
      "Most likely to lose their phone on a night out?",
      "Most likely to cry in the club bathroom?",
      "Most likely to get kicked out of a club?",
      "Most likely to flirt with the bartender?",
      "Most likely to disappear for an hour?",
      "Most likely to accidentally spend all their money?",
      "Most likely to say they’re only having one drink?",
      "Most likely to become best friends with a stranger?",
      "Most likely to overshare after two drinks?",
      "Most likely to suggest shots?",
      "Most likely to forget where they parked?",
      "Most likely to fall asleep first at a party?",
      "Most likely to accidentally start drama?",
      "Most likely to become famous?",
      "Most likely to survive a zombie apocalypse?",
      "Most likely to spend all their money on food?",
      "Most likely to laugh at the worst possible moment?",
      "Most likely to miss their alarm?",
      "Most likely to send a risky text after midnight?",
      "Most likely to trip over absolutely nothing?",
      "Most likely to lose their keys?",
      "Most likely to become a millionaire?",
      "Most likely to get way too competitive?",
      "Most likely to order takeaway at 2am?",
      "Most likely to cry at a movie?",
      "Most likely to forget someone's name immediately?",
      "Most likely to accidentally leak a secret?",
      "Most likely to become internet famous?",
      "Most likely to survive on no sleep?",
      "Most likely to get lost abroad?",
      "Most likely to binge-watch an entire series in one night?",
      "Most likely to cancel plans last minute?",
      "Most likely to flirt their way out of trouble?",
      "Most likely to become the group therapist?",
      "Most likely to accidentally break something at a party?",
      "Most likely to screenshot a conversation?",
      "Most likely to laugh during a serious moment?",
      "Most likely to spend hours on TikTok?",
      "Most likely to get caught sneaking snacks into somewhere?",
      "Most likely to start singing after a few drinks?",
      "Most likely to survive the longest in a horror movie?",
      "Most likely to become obsessed with a random hobby?",
      "Most likely to send voice notes instead of texts?",
      "Most likely to get banned from a club?",
      "Most likely to forget what they were talking about halfway through a sentence?",
      "Most likely to be late to their own wedding?",
      "Most likely to embarrass themselves in public?",
      "Most likely to accidentally text the wrong person?",
      "Most likely to become everyone's parent on a night out?",
      "Most likely to disappear and come back with food?",
  
      "Most likely to go on holiday with {player} and cause chaos?",
      "Most likely to accidentally reveal {player}'s secret?",
      "Most likely to be protected by {player} on a night out?",
      "Most likely to start a business with {player} and make it weirdly successful?",
      "Most likely to get dragged into drama because of {player}?",
      "Most likely to trust {player} with their phone?",
      "Most likely to get lost with {player} and pretend it was planned?",
      "Most likely to be in a reality show with {player}?",
      "Most likely to blame {player} for something they definitely did?",
      "Most likely to survive a horror movie only because of {player}?",
      "Most likely to start laughing just because {player} is laughing?",
      "Most likely to accidentally spend all their money while shopping with {player}?",
      "Most likely to ask {player} for life advice at 2am?",
      "Most likely to be convinced by {player} to do something chaotic?",
      "Most likely to make a secret handshake with {player}?",
      "Most likely to become famous in a duo with {player}?",
      "Most likely to get kicked out of somewhere with {player}?",
      "Most likely to share food with {player} but complain about it?",
      "Most likely to plan a night out with {player} and lose control of the plan?",
      "Most likely to make {player} laugh at the worst possible time?",
      "Most likely to become roommates with {player} and argue over snacks?",
      "Most likely to trust {player} with a secret and regret it later?"
    ],
  
    spicy: [
      "Most likely to catch feelings first?",
      "Most likely to text their ex after midnight?",
      "Most likely to flirt their way out of trouble?",
      "Most likely to kiss someone at this party?",
      "Most likely to have a secret crush in the group?",
      "Most likely to stalk someone's social media?",
      "Most likely to fall for a red flag?",
      "Most likely to have a sneaky link?",
      "Most likely to send risky texts?",
      "Most likely to get back with their ex?",
      "Most likely to accidentally expose their situationship?",
      "Most likely to flirt just for attention?",
      "Most likely to fall in love too quickly?",
      "Most likely to ghost someone accidentally?",
      "Most likely to have the most unread messages?",
      "Most likely to hide their phone screen?",
      "Most likely to kiss someone they just met?",
      "Most likely to have the wildest dating history?",
      "Most likely to fold if their crush texted right now?",
      "Most likely to cause drama in the group chat?",
      "Most likely to have a secret admirer?",
      "Most likely to flirt with the bartender?",
      "Most likely to get jealous but pretend not to care?",
      "Most likely to send paragraphs after one drink?",
      "Most likely to match with someone in this room?",
      "Most likely to accidentally leak private information?",
      "Most likely to have multiple talking stages?",
      "Most likely to say 'it's complicated' about their love life?",
      "Most likely to fall for their best friend?",
      "Most likely to flirt with someone else's crush?",
  
      "Most likely to have secret chemistry with {player}?",
      "Most likely to flirt with {player} just to see what happens?",
      "Most likely to accidentally expose {player}'s crush?",
      "Most likely to get jealous if {player} flirted with someone else?",
      "Most likely to send a risky text because {player} encouraged them?",
      "Most likely to have a situationship with someone like {player}?",
      "Most likely to ask {player} for dating advice and ignore it?",
      "Most likely to have a flirty friendship with {player}?",
      "Most likely to kiss someone after being dared by {player}?",
      "Most likely to be caught checking if {player} watched their story?",
      "Most likely to flirt better when {player} is watching?",
      "Most likely to have a secret pact with {player} about dating drama?",
      "Most likely to cause romantic chaos on a night out with {player}?"
    ]
  },

  truthOrDare: {
    classic: {
      truths: [
        "What is the most embarrassing thing you've done on a night out?",
        "Who in the room knows you best?",
        "What is a harmless secret you've never told this group?",
        "What is the worst excuse you've used to cancel plans?",
        "Who was your first crush?",
        "What is something you pretend to hate but secretly like?",
        "What is your biggest ick?",
        "What is the most awkward text you've ever sent?",
        "Who here would you trust with your phone?",
        "What is your most embarrassing drunk story?",
        "What is the weirdest thing you've ever believed?",
        "What is one thing you are terrible at but pretend you can do?",
        "What is the most childish thing you still do?",
        "What is the worst fashion choice you've ever made?",
        "Who here would survive best on a reality TV show?",
        "What is your guilty pleasure song?",
        "What is the most dramatic thing you've done for attention?",
        "What is the funniest lie you've ever told?",
        "What is something everyone else loves but you don't understand?",
        "What is the most embarrassing thing in your camera roll?",
        "What is your worst habit?",
        "Who here would you call in an emergency?",
        "What is the most ridiculous thing you've cried over?",
        "What is the strangest dream you've had?",
        "What is the worst date you've ever been on?",
        "What is something you immediately judge people for?",
        "What is the most embarrassing thing you've done in public?",
        "What is a food combination you love but others would hate?",
        "What is the most random thing you know too much about?",
        "What is your most irrational fear?",
  
        "What is one thing you think {player} is secretly good at?",
        "What was your first impression of {player}?",
        "Would you trust {player} to plan your night out?",
        "What is one thing {player} would probably beat you at?",
        "What is the funniest thing {player} has done?",
        "What is one word you would use to describe {player}?",
        "Would you trust {player} with your phone for 10 minutes?",
        "What reality TV show would {player} be funniest on?",
        "What is something {player} would be weirdly good at?",
        "What would you ask {player} if they had to answer honestly?",
        "What is one harmless secret you think {player} might have?",
        "Would you swap lives with {player} for a day?",
        "What is something {player} does that makes the group laugh?"
      ],
  
      dares: [
        "Do your best impression of someone in the room.",
        "Speak in an accent until your next turn.",
        "Swap seats with the person opposite you.",
        "Do a dramatic reading of your last text.",
        "Let the group rename you for the next 3 rounds.",
        "Take a selfie with the person on your left.",
        "Sing the chorus of the last song you listened to.",
        "Give your best runway walk across the room.",
        "Let the group choose your pose for a photo.",
        "Do your best evil laugh.",
        "Speak only in questions until your next turn.",
        "Let another player choose your next drink penalty.",
        "Do a fake acceptance speech for winning an award.",
        "Talk like a reality TV contestant for one round.",
        "Do your best dance move for 10 seconds.",
        "Let the group choose someone for you to compliment.",
        "Read your last search out loud, if you are comfortable.",
        "Make up a short rap about the person on your right.",
        "Balance something on your head for one round.",
        "Pretend to be a waiter and take everyone's fake order.",
        "Give everyone in the room a dramatic nickname.",
        "Do your best celebrity impression.",
        "Let the group pick a word you cannot say for 3 rounds.",
        "Act like you are in a perfume advert for 10 seconds.",
        "Try to make the group laugh without speaking.",
        "Talk in slow motion until your next turn.",
        "Give a weather report for tonight's party.",
        "Do your best fake proposal speech.",
        "Let the person on your left post a harmless emoji from your phone.",
        "Perform your best air guitar solo.",
  
        "Give {player} a dramatic compliment.",
        "Let {player} choose your next drink penalty.",
        "Do your best impression of {player}.",
        "Make up a theme song for {player}.",
        "Let {player} choose a word you cannot say for one round.",
        "Give {player} a fake award and make an acceptance speech for them.",
        "Tell the group why {player} would survive a zombie apocalypse.",
        "Let {player} pick your pose for a photo.",
        "Make up a dramatic nickname for {player}.",
        "Do a fake news report about something {player} did tonight.",
        "Give {player} a compliment like you are in a movie trailer.",
        "Let {player} choose your next accent.",
        "Make a 10-second advert selling {player} as a celebrity."
      ]
    },
  
    spicy: {
      truths: [
        "Have you ever had a crush on someone in this room?",
        "What is your biggest dating red flag?",
        "Who here is most your type?",
        "Have you ever gone back to someone you said you were done with?",
        "What is the flirtiest message you've ever sent?",
        "What is your guilty pleasure when it comes to dating?",
        "Have you ever fancied someone you shouldn't?",
        "What is the most attractive quality in someone?",
        "Have you ever checked someone's socials before meeting them?",
        "What is your most chaotic talking-stage story?",
        "Have you ever kissed someone and regretted it?",
        "What is the biggest green flag someone can have?",
        "Have you ever had a secret crush on a friend?",
        "What is your worst dating app experience?",
        "Who here would give the best dating advice?",
        "Have you ever lied about being over someone?",
        "What is the boldest message you've ever sent?",
        "Have you ever flirted with someone just for attention?",
        "What is your biggest turn-off?",
        "Have you ever hidden a chat from someone?",
        "What is your type, be honest?",
        "Have you ever had a situationship?",
        "Who here is most likely to break hearts?",
        "Have you ever ignored a red flag because someone was attractive?",
        "What is the most embarrassing thing you've done for someone you liked?",
        "Have you ever had a flirty friendship?",
        "What is the worst excuse you've used to avoid someone?",
        "Who here has the most mysterious love life?",
        "Have you ever sent a message then instantly regretted it?",
        "What is your most chaotic crush story?",
  
        "Would you trust {player} to give you dating advice?",
        "What do you think {player}'s biggest green flag is?",
        "What do you think {player}'s dating red flag would be?",
        "Would {player} be a good wingman or a dangerous wingman?",
        "What dating app bio would you write for {player}?",
        "Do you think {player} would be smooth or awkward on a first date?",
        "What is something about {player} that people probably find attractive?",
        "Would you trust {player} to choose someone for you to flirt with?",
        "What romantic movie role would {player} play?",
        "Do you think {player} is more likely to catch feelings or run away from them?",
        "What is one compliment you think {player} deserves?",
        "Would {player} be good at keeping a secret crush secret?",
        "Who would cause more romantic chaos: you or {player}?"
      ],
  
      dares: [
        "Give 2 sips to the person you think has the best flirting skills.",
        "Let the group choose who you should give a compliment to.",
        "Read your last sent message out loud, if you are comfortable.",
        "Send a harmless flirty emoji to someone chosen by the group.",
        "Let the group ask you one yes/no dating question.",
        "Give your best wink to the room.",
        "Tell someone in the room their best feature.",
        "Let the group choose someone for you to take a selfie with.",
        "Give 3 sips to the biggest flirt.",
        "Say your best pickup line with full confidence.",
        "Give 2 sips to someone you think has good energy.",
        "Let the person on your right choose who you compliment.",
        "Do your best romantic movie stare.",
        "Give a dramatic speech about your ideal date.",
        "Let the group decide who has the best smile.",
        "Give 2 sips to the person most likely to have a secret admirer.",
        "Say 'I have standards' like you mean it.",
        "Let the group choose your dating app bio for one sentence.",
        "Give your best slow-motion entrance.",
        "Compliment the person opposite you.",
        "Give 3 sips to the person most likely to text their ex tonight.",
        "Act out your reaction to your crush texting you.",
        "Let someone choose a flirty nickname for you for 2 rounds.",
        "Say your most confident chat-up line.",
        "Give 2 sips to the person most likely to cause romantic drama.",
        "Do your best dramatic hair flip.",
        "Let the group vote who has the best rizz.",
        "Give a fake toast to your future soulmate.",
        "Take 2 sips if you refuse to answer a spicy question.",
        "Give 3 sips to whoever you think is the biggest heartbreaker.",
  
        "Give {player} a dramatic romantic-movie compliment.",
        "Let {player} choose who you give 2 sips to.",
        "Say your best pickup line to {player}.",
        "Let {player} choose your flirty nickname for 2 rounds.",
        "Give {player} 2 sips if you think they have good energy.",
        "Tell {player} their best feature.",
        "Let {player} rate your wink out of 10.",
        "Do your best romantic movie stare at {player}.",
        "Give a fake toast to {player}'s future love life.",
        "Let {player} choose a yes/no dating question for you.",
        "Compliment {player} like you are trying to win them over.",
        "Give 2 sips to {player} if you think they would be a good wingman.",
        "Let {player} choose who has the best rizz."
      ]
    }
  },
  
  neverHaveIEver: {
    classic: [
      "Never have I ever faked being sick to get out of plans.",
      "Never have I ever stalked someone on social media for over an hour.",
      "Never have I ever sent a risky text and regretted it instantly.",
      "Never have I ever fallen asleep drunk.",
      "Never have I ever kissed someone I just met.",
      "Never have I ever lied on a dating app.",
      "Never have I ever ghosted someone.",
      "Never have I ever drunk-texted an ex.",
      "Never have I ever blamed a fart on someone else.",
      "Never have I ever pretended to know a song in the club.",
      "Never have I ever laughed at the wrong moment.",
      "Never have I ever cancelled plans last minute.",
      "Never have I ever screenshotted a conversation.",
      "Never have I ever spent too much money on food delivery.",
      "Never have I ever pretended to be busy to avoid someone.",
      "Never have I ever forgotten someone's name straight after meeting them.",
      "Never have I ever cried over something ridiculous.",
      "Never have I ever eaten food I dropped on the floor.",
      "Never have I ever stayed up all night by accident.",
      "Never have I ever lied about being on my way.",
  
      "Never have I ever thought {player} would be trouble on a night out.",
      "Never have I ever wanted to swap lives with {player} for a day.",
      "Never have I ever laughed at something {player} said when I shouldn't have.",
      "Never have I ever thought {player} would survive longest in a horror movie.",
      "Never have I ever wanted {player}'s confidence.",
      "Never have I ever trusted {player} more than I should.",
      "Never have I ever thought {player} would be fun to travel with.",
      "Never have I ever wondered what {player}'s camera roll looks like.",
      "Never have I ever thought {player} would accidentally start drama.",
      "Never have I ever wanted {player} on my team in a game.",
      "Never have I ever thought {player} gives good advice.",
      "Never have I ever thought {player} would be dangerous with unlimited money.",
      "Never have I ever thought {player} would be famous one day."
    ],
  
    spicy: [
      "Never have I ever kissed two people in the same night.",
      "Never have I ever had a sneaky link.",
      "Never have I ever sent a risky photo.",
      "Never have I ever hooked up in public.",
      "Never have I ever flirted to get free drinks.",
      "Never have I ever had a friends-with-benefits situation.",
      "Never have I ever kissed my best friend.",
      "Never have I ever lied about my body count.",
      "Never have I ever had a one-night stand.",
      "Never have I ever been caught doing something spicy.",
      "Never have I ever had a secret crush in the group.",
      "Never have I ever gone back to someone I said I was done with.",
      "Never have I ever flirted with someone just for attention.",
      "Never have I ever checked if someone watched my story.",
      "Never have I ever hidden a chat from someone.",
  
      "Never have I ever wondered if {player} has a secret crush.",
      "Never have I ever thought {player} would be dangerous on a dating app.",
      "Never have I ever thought {player} would be a good flirt.",
      "Never have I ever wanted dating advice from {player}.",
      "Never have I ever thought {player} would break hearts.",
      "Never have I ever thought {player} has mysterious romantic energy.",
      "Never have I ever thought {player} would be smooth on a first date.",
      "Never have I ever thought {player} would have a secret admirer.",
      "Never have I ever wondered what {player}'s type is.",
      "Never have I ever thought {player} would cause romantic drama.",
      "Never have I ever thought {player} would be a good wingman.",
      "Never have I ever thought {player} would fold if their crush texted.",
      "Never have I ever thought {player} gives flirty energy."
    ]
  },
    
    imposter: {
      classic: [
    { word: "Pizza", hint: "Food" },
    { word: "Beach", hint: "Place" },
    { word: "Football", hint: "Sport" },
    { word: "Netflix", hint: "Entertainment" },
    { word: "Airport", hint: "Place" },
    { word: "Coffee", hint: "Drink" },
    { word: "TikTok", hint: "App" },
    { word: "Birthday", hint: "Event" },
    { word: "Cinema", hint: "Place" },
    { word: "Burger", hint: "Food" },
    { word: "Gym", hint: "Place" },
    { word: "Laptop", hint: "Object" },
    { word: "Ice Cream", hint: "Food" },
    { word: "Library", hint: "Place" },
    { word: "Concert", hint: "Event" },
    { word: "Chocolate", hint: "Food" },
    { word: "Taxi", hint: "Transport" },
    { word: "Museum", hint: "Place" },
    { word: "Hotdog", hint: "Food" },
    { word: "Bus Stop", hint: "Place" },
    { word: "Pool", hint: "Place" },
    { word: "Soda", hint: "Drink" },
    { word: "Park", hint: "Place" },
    { word: "Movie Ticket", hint: "Object" },
    { word: "Shopping Mall", hint: "Place" },
    { word: "Candy", hint: "Food" },
    { word: "Skateboard", hint: "Object" },
    { word: "Chocolate Cake", hint: "Food" },
    { word: "Concert Ticket", hint: "Object" }
  ],
  
  spicy: [
    { word: "First Date", hint: "Dating" },
    { word: "Crush", hint: "Romance" },
    { word: "Red Flag", hint: "Dating" },
    { word: "Flirting", hint: "Dating" },
    { word: "Ex", hint: "Relationship" },
    { word: "Situationship", hint: "Dating" },
    { word: "Secret Crush", hint: "Romance" },
    { word: "Jealousy", hint: "Relationship" },
    { word: "Love Island", hint: "TV / Dating" },
    { word: "Dating App", hint: "Dating" },
    { word: "Kiss", hint: "Romance" },
    { word: "Hookup", hint: "Romance" },
    { word: "Texting Crush", hint: "Romance" },
    { word: "Flirt Text", hint: "Romance" },
    { word: "Breakup", hint: "Relationship" },
    { word: "First Kiss", hint: "Romance" },
    { word: "Crush Confession", hint: "Romance" },
    { word: "Steamy Message", hint: "Romance" },
    { word: "Late Night Call", hint: "Relationship" },
    { word: "Secret Rendezvous", hint: "Romance" },
    { word: "Romantic Gesture", hint: "Romance" },
    { word: "Blind Date", hint: "Dating" },
    { word: "Love Letter", hint: "Romance" },
    { word: "Cheeky Compliment", hint: "Romance" },
    { word: "Flirty Emoji", hint: "Romance" },
    { word: "Secret Relationship", hint: "Romance" },
    { word: "Crush Crush", hint: "Romance" },
    { word: "Steal a Kiss", hint: "Romance" },
    { word: "Unexpected Date", hint: "Romance" },
    { word: "Romantic Text", hint: "Romance" }
      ]
    },

    wouldYouRather: {
      classic: [
        "Would you rather be invisible or be able to fly?",
        "Would you rather always have bad Wi-Fi or always have bad cell service?",
        "Would you rather have a rewind button or a pause button in your life?",
        "Would you rather always be too hot or too cold?",
        "Would you rather fight one horse-sized duck or 100 duck-sized horses?",
        "Would you rather live without music or live without movies?",
        "Would you rather never sleep or never eat again?",
        "Would you rather have super strength or super speed?",
        "Would you rather be stuck in a lift or stuck in traffic?",
        "Would you rather have unlimited money or unlimited time?",
        "Would you rather always be late or always be early?",
        "Would you rather lose your phone or lose your wallet?",
        "Would you rather be famous or be rich?",
        "Would you rather never use social media again or never watch TV again?",
        "Would you rather have a pet dinosaur or a pet dragon?",
        "Would you rather live in the mountains or by the beach?",
        "Would you rather be able to talk to animals or speak every language?",
        "Would you rather have a photographic memory or be able to forget anything you want?",
        "Would you rather always have hiccups or always feel sleepy?",
        "Would you rather only be able to whisper or only be able to shout?",
        "Would you rather live in a world without pizza or without chocolate?",
        "Would you rather never feel pain or never feel fear?",
        "Would you rather explore the deepest ocean or outer space?",
        "Would you rather have a personal chef or a personal driver?",
        "Would you rather read minds or see the future?",
        "Would you rather be able to teleport or time travel?",
        "Would you rather live without the internet or without your phone?",
        "Would you rather always win arguments or always have the last word?",
        "Would you rather live in a treehouse or a houseboat?",
        "Would you rather always have to sing instead of speak or dance everywhere you go?",
        "Would you rather find true love or £1 million?",
        "Would you rather never have to wait in line or never have to pay for anything?",
        "Would you rather live in the past or the future?",
        "Would you rather have a job you love with little pay or a job you hate with high pay?",
        "Would you rather travel to every country or live in one exotic place forever?",
        "Would you rather have perfect health or perfect wealth?",
        "Would you rather always be underdressed or overdressed?",
        "Would you rather only eat sweet or only eat savoury food for life?",
        "Would you rather be feared or loved?",
        "Would you rather have a private island or a private jet?",
    
        "Would you rather swap phones with {player} for 10 minutes or let the group read your last message?",
        "Would you rather go on holiday with {player} or plan a party with {player2}?",
        "Would you rather let {player} choose your outfit or your next text?",
        "Would you rather be stuck in a lift with {player} or lost abroad with {player2}?",
        "Would you rather have {player} control your playlist for a week or choose your dinner for a week?",
        "Would you rather have {player} read your mind for one minute or read your last three searches?",
        "Would you rather swap lives with {player} for a day or swap phones with them for an hour?",
        "Would you rather have {player} plan your birthday or choose your next holiday?",
        "Would you rather have {player} as your lawyer or {player2} as your therapist?",
        "Would you rather let {player} choose your next hairstyle or your next Instagram caption?",
        "Would you rather be on a reality show with {player} or survive a zombie apocalypse with {player2}?",
        "Would you rather let {player} spend £100 of your money or send one message from your phone?",
        "Would you rather have {player} narrate your life for a day or follow you around with a camera?",
        "Would you rather have to copy {player}'s laugh for a week or dress like them for a week?",
        "Would you rather let {player} choose your dare or let {player2} choose your drink penalty?"
      ],
    
      spicy: [
        "Would you rather kiss someone in the room or get kissed by someone blindfolded?",
        "Would you rather text your crush something embarrassing or have them text you?",
        "Would you rather never get a drink at a party or always spill yours?",
        "Would you rather reveal your most embarrassing secret or hear someone else’s?",
        "Would you rather flirt with your crush or be flirted with?",
        "Would you rather go on a secret date or a public date?",
        "Would you rather get caught sneaking a kiss or sneaking a text?",
        "Would you rather send a flirty emoji or a risky meme?",
        "Would you rather get caught staring at someone or get caught texting someone?",
        "Would you rather kiss in the rain or under the stars?",
        "Would you rather have a crush on your best friend or your enemy?",
        "Would you rather have a romantic disaster or a perfect awkward moment?",
        "Would you rather be asked out by someone shy or someone bold?",
        "Would you rather accidentally reveal a secret crush or keep it forever?",
        "Would you rather receive a love letter or a secret gift?",
        "Would you rather flirt online or in person?",
        "Would you rather someone confess to you or you confess to them?",
        "Would you rather go on a romantic picnic or a late-night drive?",
        "Would you rather kiss in a crowded place or in complete privacy?",
        "Would you rather send a flirty text to your crush or receive one?",
        "Would you rather get caught checking someone out or be ignored when checking someone out?",
        "Would you rather have a secret admirer or a public admirer?",
        "Would you rather go on a blind date or set up a friend on a blind date?",
        "Would you rather confess your crush or have them confess to you?",
        "Would you rather have a crush on two people at once or none?",
        "Would you rather be kissed unexpectedly or kiss unexpectedly?",
        "Would you rather flirt over text or in person?",
        "Would you rather receive a romantic surprise or plan one?",
        "Would you rather have a secret crush or a public crush?",
        "Would you rather kiss your crush or hold hands?",
    
        "Would you rather have {player} choose who you flirt with or choose your pickup line?",
        "Would you rather go on a fake date with {player} or let {player2} write your dating profile?",
        "Would you rather let {player} read your last flirty text or your last deleted message?",
        "Would you rather have {player} reveal your type or guess your crush?",
        "Would you rather let {player} choose your next dating app photo or your bio?",
        "Would you rather flirt with {player} for 30 seconds or let them flirt with you?",
        "Would you rather let {player} send a harmless emoji from your phone or choose who you compliment?",
        "Would you rather have {player} rate your rizz or choose your flirty nickname?",
        "Would you rather be wingmanned by {player} or set up by {player2}?",
        "Would you rather have {player} guess your red flag or your biggest green flag?",
        "Would you rather let {player} ask you one spicy yes/no question or let the group ask one?",
        "Would you rather have to compliment {player} dramatically or let {player} compliment you?",
        "Would you rather let {player} choose who you give 2 sips to or who you take a selfie with?",
        "Would you rather be caught flirting with {player} or caught talking about them?",
        "Would you rather let {player} expose your dating type or your most chaotic crush story?"
      ]
    },
    
    dareRoulette: {
      classic: [
        "Sing the chorus of your favourite song.",
        "Do your best dance for 10 seconds.",
        "Speak in an accent until your next turn.",
        "Pretend to be a waiter and take fake orders.",
        "Give someone in the room a compliment.",
        "Act like a celebrity for 15 seconds.",
        "Do your best impression of someone in the room.",
        "Balance something on your head for 10 seconds.",
        "Tell a joke that makes everyone laugh.",
        "Say a tongue-twister three times fast.",
        "Do your best runway walk across the room.",
        "Give everyone in the room a dramatic nickname.",
        "Talk like a reality TV contestant for one round.",
        "Do your best evil laugh.",
        "Pretend you just won an award and give a speech.",
    
        "Give {player} a compliment.",
        "Let {player} choose your next dare.",
        "Do your best impression of {player}.",
        "Make up a dramatic nickname for {player}.",
        "Let {player} pick a word you cannot say for one round.",
        "Make up a short song about {player}.",
        "Give {player} a fake award and explain why they won.",
        "Let {player} choose your pose for a photo.",
        "Do a fake news report about {player}.",
        "Tell the group why {player} would survive a zombie apocalypse."
      ],
    
      spicy: [
        "Whisper a secret to someone nearby.",
        "Send a flirty emoji to someone in the room.",
        "Give someone a playful dare in private.",
        "Kiss your own hand like it’s someone else’s.",
        "Tell someone their best feature.",
        "Flirt with the person to your left for 10 seconds.",
        "Text a crush something bold.",
        "Pretend to confess a secret crush.",
        "Draw a heart somewhere visible on yourself.",
        "Give a cheeky compliment to someone.",
        "Do your best romantic movie stare.",
        "Say your best pickup line with full confidence.",
        "Let the group choose your flirty nickname.",
        "Give a dramatic toast to your future soulmate.",
        "Act out your reaction to your crush texting you.",
    
        "Give {player} a cheeky compliment.",
        "Let {player} choose who you flirt with for 10 seconds.",
        "Say your best pickup line to {player}.",
        "Let {player} choose your flirty nickname.",
        "Tell {player} their best feature.",
        "Give {player} 2 sips if you think they have good energy.",
        "Let {player} rate your wink out of 10.",
        "Do your best romantic movie stare at {player}.",
        "Let {player} choose who gets a cheeky compliment.",
        "Give a dramatic toast to {player}'s love life."
      ]
    },

    kingCup: {
      classic: {
        rules: {
          A: "Waterfall — Everyone starts drinking. You can stop when the person before you stops.",
          2: "You — Choose someone to drink.",
          3: "Me — You drink.",
          4: "Floor — Last player to touch the floor drinks.",
          5: "Guys — All guys drink.",
          6: "Girls — All girls drink.",
          7: "Heaven — Last player to point up drinks.",
          8: "Mate — Choose a drinking buddy. They drink whenever you drink.",
          9: "Rhyme — Say a word. Everyone must rhyme with it. First to fail drinks.",
          10: "Categories — Pick a category. Everyone names something in it. First to fail drinks.",
          J: "Make a Rule — Create a rule everyone must follow.",
          Q: "Question Master — Anyone who answers your questions drinks.",
          K: "King — Pour some drink into the King’s Cup. The 4th King drinks it!"
        }
      },
    
      spicy: {
        rules: {
          A: "Waterfall — Everyone starts drinking. You can stop when the person before you stops.",
          2: "You — Choose someone to drink.",
          3: "Me — You drink.",
          4: "Floor — Last player to touch the floor drinks.",
          5: "Flirt — Give someone a cheeky compliment or drink.",
          6: "Sip and Tell — Share a harmless secret or drink.",
          7: "Heaven — Last player to point up drinks.",
          8: "Mate — Choose a drinking buddy. They drink whenever you drink.",
          9: "Rhyme — Say a word. Everyone must rhyme with it. First to fail drinks.",
          10: "Categories — Pick a spicy-safe category. First to fail drinks.",
          J: "Make a Rule — Create a rule everyone must follow.",
          Q: "Question Master — Anyone who answers your questions drinks.",
          K: "King — Pour some drink into the King’s Cup. The 4th King drinks it!"
        }
      }
    },
      knowMeBetter: {
        classic: [
          "What is {player}'s go-to takeaway order?",
          "What is {player}'s favourite drink?",
          "What song would {player} always sing at karaoke?",
          "What is {player}'s biggest ick?",
          "What would {player} spend £100 on first?",
          "What is {player}'s comfort food?",
          "What would instantly annoy {player}?",
          "What is {player}'s most used phrase?",
          "What app does {player} use the most?",
          "What is {player}'s dream holiday?",
          "What would {player} order at a bar?",
          "What film or show could {player} rewatch forever?",
          "What is {player}'s worst habit?",
          "What is {player}'s hidden talent?",
          "What is {player}'s favourite snack?",
          "What would {player} do first after winning the lottery?"
        ],
        spicy: [
          "What is {player}'s biggest red flag?",
          "What is {player}'s biggest green flag?",
          "What type of person does {player} usually fall for?",
          "What is {player}'s most chaotic night out habit?",
          "Who would {player} drunk text?",
          "What is {player}'s flirting style?",
          "What gives {player} the ick instantly?",
          "What is {player}'s ideal date?",
          "What would make {player} leave someone on read?",
          "What is {player}'s toxic trait?"
        ]
      }
    };